ejecución pruebas unitarias con Junit en pipeline

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -30,6 +30,17 @@ jobs:
     - name: Build with Maven
       run: mvn -B package --file pom.xml
 
-    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
-    - name: Update dependency graph
-      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
+    - name: Build with Gradle
+      run: ./gradlew build
+
+    - name: Run JUnit tests
+      run: |
+        ./gradlew test
+        test_result=$?
+        if [ $test_result -ne 0 ]; then
+          echo "Tests failed with exit code $test_result"
+          exit $test_result
+        fi
+
+    - name: Fail CI if build failed
+      uses: actions/fail-if-build-failed@v1
